apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sb-web
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: sb-web
    spec:
      containers:
      - name: sb-web
        image: localhost:5000/sb-web
